### PR TITLE
Rename the desktop entry file to match the application ID

### PR DESCRIPTION
**Pull request by cheese**
GNOME Shell requires this to load application icon and prepare
sandboxing[1].

[1] https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

### CODE REVIEW

**Comment by u-235** [comment]
But this is a requirement for GTK-based applications, right? Is the sandbox a flatpack? Wouldn't it be better to rename the file when bundling?

**Comment by cheese** [comment]
> But this is a requirement for GTK-based applications, right?

Not just for GTK-based applications. It is for any application that aim for better integration with GNOME Shell.

> Is the sandbox a flatpack?

Here does not mean for the flatpak level sandboxing. Just the GNOME Shell level. But renaming the desktop file is even obligatory for flatpak.

> Wouldn't it be better to rename the file when bundling?

Renaming will make all packagers happy. Casual packager may not even know what the application ID is.

**Comment by cheese** [comment]
> But this is a requirement for GTK-based applications, right?

Not just for GTK-based applications. It is for any application that aim for better integration with GNOME Shell.

> Is the sandbox a flatpack?

Here does not mean for the flatpak level sandboxing. Just the GNOME Shell level. But renaming the desktop file is even obligatory for flatpak.

> Wouldn't it be better to rename the file when bundling?

Renaming will make all packagers happy. Casual packager may not even know what the application ID is.

**Comment by cheese** [comment]
This is not the best solution. Upstream should decide an explicit application ID and set it by `QGuiApplication::setDesktopFileName`. And then rename the desktop entry file according to that.

For example:

```
#if QT_VERSION >= QT_VERSION_CHECK(5, 7, 0)
  QGuiApplication::setDesktopFileName("net.kchmviewer.KchmViewer");
#endif
```

**Pull request closed without merging**
